# FailSafe Ethical Configuration
# Comprehensive settings for bias detection, privacy, and compliance

# Bias Detection & Fairness
bias_threshold: 0.2
retention_days: 30
consent_required: true

fairness:
  demographic_parity_target: 0.0
  equalized_odds_threshold: 0.1
  calibration_threshold: 0.05
  protected_attributes: ["gender", "race", "age", "religion", "nationality"]
  bias_mitigation_strategies:
    - "demographic_parity"
    - "equalized_odds"
    - "calibration"
  source_diversity_boost: 0.1
  global_south_priority: true
  cultural_sensitivity_check: true

# Privacy & Data Protection
privacy:
  anonymize_logs: true
  pii_redaction: true
  data_encryption: true
  encryption_algorithm: "AES-256"
  anonymization_methods:
    - "tokenization"
    - "hashing"
    - "generalization"
  data_retention_policy:
    analysis_logs: "30_days"
    user_feedback: "90_days"
    model_training_data: "1_year"
    audit_trails: "7_years"
  gdpr_compliance:
    right_to_erasure: true
    data_portability: true
    consent_management: true
    breach_notification: true

# Legal & Compliance
legal:
  medical_disclaimer: "Không thay thế tư vấn chuyên môn"
  gdpr_compliant: true
  hipaa_compliant: false
  ccpa_compliant: true
  disclaimer_texts:
    medical: "Thông tin này không thay thế tư vấn y tế chuyên nghiệp"
    legal: "Thông tin này không phải là tư vấn pháp lý"
    financial: "Thông tin này không phải là tư vấn tài chính"
  jurisdiction: "global"
  content_moderation:
    hate_speech_detection: true
    violence_detection: true
    misinformation_threshold: 0.8

# Rate Limiting & Abuse Prevention
rate_limit:
  max_per_minute: 120
  max_per_hour: 1000
  max_per_day: 10000
  burst_limit: 20
  ip_whitelist: []
  ip_blacklist: []
  user_tier_limits:
    free: 100
    premium: 1000
    enterprise: 10000
  abuse_detection:
    suspicious_pattern_threshold: 0.7
    auto_block_duration: "1_hour"
    manual_review_threshold: 0.9

# Logging & Monitoring
logging:
  level: INFO
  structured_logging: true
  log_format: "json"
  sensitive_data_masking: true
  audit_logging: true
  performance_logging: true
  error_tracking: true
  log_retention:
    debug: "7_days"
    info: "30_days"
    warning: "90_days"
    error: "1_year"

# Verification & Anti-Hallucination
verification:
  calibration:
    a: 6.0
    b: 0.6
    multi_source_boost: 0.05
    decent_hit_threshold: 0.6
    truthfulqa_calibration: true
  anti_hallucination:
    max_retries: 1
    retry_threshold: 0.7
    min_improvement: 0.05
    self_reflection_enabled: true
    multi_agent_cross_check: true
    retrieval_first_pipeline: true
    structured_output_validation: true
  confidence_thresholds:
    high: 0.8
    medium: 0.6
    low: 0.4
    minimum: 0.1
  evidence_requirements:
    min_sources: 2
    min_confidence: 0.6
    cross_validation_required: true

# Retrieval & Caching
retrieval:
  cache:
    ttl_seconds: 600
    max_entries: 256
    compression_enabled: true
  source_prioritization:
    academic_sources: 1.0
    government_sources: 0.9
    news_sources: 0.7
    social_media: 0.3
    user_generated: 0.1
  cross_lingual_mapping: true
  provenance_tracking: true
  source_verification: true

# Caching System
cache:
  max_memory_items: 1000
  memory_ttl_seconds: 300
  disk_ttl_seconds: 3600
  max_disk_size_mb: 100
  compression: true
  eviction_policy: "lru"
  distributed_caching: false
  cache_warming: true

# AI Detection & Content Moderation
ai_detection:
  multi_signal_approach: true
  ensemble_voting: true
  active_learning: true
  noise_injection_test: true
  detection_methods:
    - "roberta_detector"
    - "stylometry_analysis"
    - "metadata_check"
    - "perplexity_analysis"
  thresholds:
    ai_generated: 0.7
    human_written: 0.3
    uncertain: 0.4

# Multilingual Support
multilingual:
  supported_languages: ["en", "vi", "es", "fr", "de", "zh", "ja", "ko", "ar", "hi"]
  auto_detection: true
  translation_enabled: true
  cross_lingual_embeddings: true
  cultural_adaptation: true
  language_specific_models: true

# Performance & Optimization
performance:
  early_exit_enabled: true
  model_quantization: true
  batch_processing: true
  async_processing: true
  memory_optimization: true
  gpu_utilization: "auto"
  cpu_cores: "auto"

# Security
security:
  authentication_required: false
  api_key_required: false
  rate_limiting: true
  input_validation: true
  output_sanitization: true
  sql_injection_protection: true
  xss_protection: true
  csrf_protection: true
  encryption_at_rest: true
  encryption_in_transit: true

# Development & Testing
development:
  debug_mode: false
  test_mode: false
  mock_services: false
  synthetic_data_generation: true
  adversarial_testing: true
  load_testing: true
  unit_testing: true
  integration_testing: true

# Monitoring & Alerting
monitoring:
  health_checks: true
  performance_metrics: true
  error_tracking: true
  alerting: true
  dashboard: true
  log_aggregation: true
  metrics_export: true
  alert_channels:
    - "email"
    - "slack"
    - "webhook"


